# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=50, verbose_name='文件路径'),
        ),
    ]
